### ISSUE TITLE
Tracking operation state i.e. pending/attempted and throwing exception on collapse if insert was attempted and delete tries to collapse it (To prevent orphan on server)

### ISSUE THREAD

**Issue by yavorg** [Azure/azure-mobile-services#413]
If an insert has been attempted but timed out or network connectivity error caused us to lose the response then delete can collapse and cancel the insert while it may have already been completed on server leaving an untracked orphan on the client. To avoid such a problem we need to track operation state i.e. pending, attempted, done. See 10a362eb for details.

**Comment by ysxu** [comment]
@marianosz investigated and this does not apply to android sdk

**Comment by phvannor** [comment]
Can you provide details on how this does not apply?

**Comment by phvannor** [comment]
Also "while it may have already been completed on server leaving an untracked orphan on the client", is a little unclear.  It should read, "while it may have already been completed on server, losing track of the user's delete request. The server will keep that item, and the client state will be incorrect until the next time the item is modified."

**Comment by ysxu** [comment]
@marianosz can you follow up on this?

**Comment by marianosz** [comment]
Our implementation keeps all the offline operations on a queue.
When the push comes, the operations are iterated, and one by one send to the server, and after that removed from the queue, no matter that exists an error or not.
If the insert operation is waiting to be processed and a delete operation appears, the insert operation will be collapsed and both operation will be discarted.
If the insert operation begin to be processed, it will be locked and there is no way to be collapsed.
Summarizing, there is no way to the delete operation to collapse on a failed insert operation, so we are never going to find orphan server elements on this scenario.

**Comment by masojus** [comment]
I'm not sure why the Android tag was added here, but the commit referenced is all related to the Managed SDK, so I'll chime in here to say that I've seen the .NET SDK attempt to collapse operations onto stale InsertOperations, regardless of success or not, due to a few race conditions that exist. Also, in common cases we can see operations not get removed from the OperationQueue because their operation version is bumped on another thread, or stale operations are shoved back into the queue accidentally during an operation update that happens due to a race condition. In short, the scenario described in this issue is at least a subset of issue #615 which I opened to talk about behavior I demonstrate in the unit test in pull request #614. Please take a look at that issue and pull request for more information.  Thanks!

**Comment by phvannor** [comment]
@masojus This issue is tracking a bug fix made to the managed SDK that needed to be checked if  Android had the same bug.  Feel free to add any additional context to #615 as needed then so it can be looked at for the managed code base.

**Comment by phvannor** [comment]
@marianosz When you say "after that removed from the queue, no matter that exits an error or not", are you saying if your insert comes back you always remove it from the queue?

THat doesn't sound right, so can you confirm?

Specifically, in this case the workflow is:
- User call Push
- Insert locked, and sent to server
- Network times out (no connection)
- Insert should be preserved to be tried again (it may or may not have actually run)
- User calls delete, error thrown / a delete replaces the queued insert.

Can you outline how the Android implementation plays out here?  What allows the user to replay the insert that timed out?

**Comment by masojus** [comment]
@phvannor Thanks for explaining why the Android tag was there. I have a colleague working on checking the scenario in issue #615 on the Android platform, so I'm sure he'll chime in with his findings.

**Comment by marianosz** [comment]
If the error is a Network error or a Authentication Error, the operation is preserved on the queue and can be collapsed.
If the error is from another kind (for example wrong table name on server) the operation is removed.

So, what we can do is if the operation was preserved on the queue because a Network or Authentication error, if a delete appears, it wouldn't be allowed to collapse to a operation that was involved in a previous push operation with error (Network or Authentication).
Is that ok?
