### ISSUE TITLE
Azure Mobile Serivces .NET Backend currently unusable (1.0.447)

### ISSUE THREAD

**Issue by apollyonbob** [Azure/azure-mobile-services#551]
So it started with an unusual problem where for some reason my database initializer kept trying to access Master, and failing. That lead to a problem with my Portal. Which lead to tech support asking me to upgrade packages.

Debugging .NET Backend is nearly impossible for two reasons: One, you can't update anything ever and two, the source code is only available in source symbol files, which sometimes don't work.

Right now, if you download a .NET Backend solution from Azure Mobile Service, go to the Solution, Manage NuGet packages, and click Update All, it breaks. With this:

**Method not found: 'Void System.IdentityModel.Tokens.JwtSecurityTokenHandler.set_CertificateValidator(System.IdentityModel.Selectors.X509CertificateValidator)'.**

If you cannot replicate this, I will send a video of it happening, if that helps. (For replication, when you first Update All, it adds an extra bindingRedirect for Microsoft.Data.OData and EDM in the web.config, then throws an error. If you simply delete these extra bindingRedirects, you will then get the Method Not Found error.)

This is _completely unacceptable._ This bug has existed for multiple releases and continues to exist. It seemed to be recognized as a bug, but then support for it stopped. The solution CANNOT be "Don't update this or that NuGet package." I'm sorry, but that is not a tenable solution for even the medium term.

I don't know if you are aware, but more than .NET Backend uses OWIN. More than .NET Backend uses NuGet packages. And these packages (like SignalR) have dependencies, and when I need to upgrade a package, it will upgrade its dependencies. And guess what? That then breaks .NET Backend because .NET Backend 1) _Doesn't have it's dependencies set properly_ (this has been a big problem for several versions) and 2) Has therefore been broken for months. _Months._

We need either the source code for .NET Backend so we can fix it ourselves, or we need .NET Backend fixed in such a way that you can update all packages and have it work. We need communication that these issues are _recognized,_ and _when_ they are going to be fixed.

.NET Backend is not realistically usable until this problem is fixed. Every time I try to actually use it in the real world, I keep running into these types of issues. When I try to debug them, I keep running into issues debugging. It's been _months_ of banging my head against the wall trying to get this working and I've finally just come to the conclusion that, right now, it doesn't. It just _doesn't work._

Sorry if some of my frustration has leaked into this post. I tried to keep it dispassionate. But you have to understand how teeth-clenchingly frustrating this entire experience has been. In my near decade of .NET programming experience, this has been the worst - well, no, I had to make SSRS reports for like 6 months. That was worse. Anyway, this has been a very bad experience. I just want it to get better so I can actually _accomplish_ something. I've gotten nowhere on my project (and, by extension, my now aborted attempt at a business) because I spent all my time trying to get AMS to work.

However, I would really _like_ for it to work. So, before I ditch AMS completely to just put a Web API on a Azure Website and figure out the auth stuff for myself, I thought I'd take one last shot at trying to get some kind of support. So how about it? Any chance that .NET Backend is going to be fixed in the near term?

**Comment by IlyaTsilikov** [comment]
The problem seems to be the same I've mentioned <a href="https://github.com/Azure/azure-mobile-services/issues/463">before</a> (and also <a href="https://github.com/Azure/azure-mobile-services/issues/542">here</a> that it seems to be still not fixed although one more version was released). So the solution is to downgrade the packages versions as it's described at the link above.

**Comment by apollyonbob** [comment]
Unfortunately that's not a long term solution as it would essentially mean I can never upgrade anything, because of interdependencies. So that's okay for a short-term work around, but we've passed the point of "short term workaround."

**Comment by apollyonbob** [comment]
Also I should reiterate that my point is not that there is this bug or that bug. My point is that actually using the .NET Backend in a practical, real-world scenario to build an actual product is not currently feasible. 

The problems extend beyond a particular bug, and into service, support, communication and guidance. .NET Backend is a framework level product - that is to say, you typically design around the idea of using it. When you're just using some add-on, it's fine for it to be pretty much unsupported. But when you're using a framework around which you will design your whole app, it can't be unsupported. There needs to be communication from the developers about what issues they're working on, mitigation/workarounds in the meanwhile, when they're next release is going to be, etc. etc.

So again, my point is less about this particular (albeit high severity) bug, and more about the fact that in its current state, with the current level of support, it's just a really bad idea to try to use it. That's obviously something that I would like to see changed, because I _would_ like to use it.

**Comment by lindydonna** [comment]
Thanks for taking the time to leave feedback, and I’m sorry to hear you spent so much time on this!  I totally agree with you, the NuGet package update problem is a really big issue--probably our top user complaint. 

The problem is that if you Update All, you can end up with a different version of a package than what we have hosted in Azure. So, you'll get runtime errors once you publish your service.  We are actually in the process of making this less error-prone by updating the NuGet package specs to hardcode the exact version of all dependencies. These updated packages should be out within a month. 

If you’re interested, we can give you access to the pre-release packages and you can try out the experience (but only locally—you wouldn’t be able to deploy because the hosting environment doesn’t have the latest packages).

Currently this will be the best solution, and I’ll update this issue once we have a fix. However, we have also been investigating a design that will give developers more control over what is deployed and what packages can be referenced. We don't have a timeframe for this, however.

In the meantime, the best workaround is to NOT Update All, but rather update one of the leaf packages in the .NET backend (such as .entities) and it will pull in updates to dependencies. Then, you can update any other packages that you know are unrelated. I realize this is annoying, but at least it’s relatively easy to get your project back into a good state.

Another option is for you to create a new service project by using the Quickstart tab in the portal. Then, look at the packages.config file and see if any of the packages are newer than yours. If the .NET backend ones have the same version, then you should only update packages that you are sure are totally unrelated.

This is not a great workaround, I realize. People are used to Update All working just fine, and it can be quite surprising (and confusing!) that it causes so many problems. 

In terms of the symbol files not working, could you note which assembly version you are having a problem with?  We'll verify that they have been published correctly. 

With regard to communication about bugs and workarounds, this is definitely something we can improve. We actively monitor all forum conversations and bug reports and try to be as open as possible. I think the problem here is that we don’t have an issue tracker for the .NET backend, just the client SDKs. So, for the client SDKs, you can find out what bugs are being worked on and whether they have been fixed in master, but not released, etc. 

We should follow this same process for the backend, and just manually update bugs as we fix in our private repository. We’ll also try to give a best estimate on release date. Generally we release backend updates every 4 weeks, but that can vary quite a bit, depending on how many bugfixes are in a given payload. However, when we find a major runtime bug, we do a rapid update and immediately refresh our hosting environment.

Sorry for the delayed response, but I wanted to be sure to give you an accurate and through answer. Please let me know if you have any follow-up questions or feedback.

**Comment by apollyonbob** [comment]
Thanks for your detailed reply, I really appreciate it. I had forgotten about the limitation of the AMS environment not having the latest versions of certain packages. Part of the confusion there is that upgrading the Client SDK will also cause chain reaction upgrades, because the Client SDK will have minimums higher than what the .NET Backend has as requirements. To clarify, I understand why the Client SDK and Backend would have totally different dependencies - but it does make it even more confusing as most of the examples have both Client and Backend in the same solution. Hardening the NuGet dependencies would help a great deal here. While it will be somewhat annoying to attempt to upgrade and get shut down, it would be totally worth it because that would at least prevent the packages from getting into a broken state. As you can imagine, the only way for me to untangle this would be to download the sample and swap things around. 

I'm very much interested in access to the pre-release packages though. I'm not going live any time soon so it's fine that I can't deploy them. 

Part of the problem is that I'm trying to use SignalR over AMS. This is supposedly supported, but I will have to double check the dependencies, because if I'm remembering correctly, the ultimate break that made it unusable for me went something like this:

Upgrade SignalR AMS package -> Requires SignalR over Azure upgrade -> Requires Azure SDK upgrade -> Requires dependency that breaks AMS.

This is what I meant by "don't upgrade" not working for me. The SignalR AMS package is necessary to accomplish my goals. But I can do more research on that and post it here, if you'd like. I'll also get a more detailed repro of my problems with the symbol server. It wasn't necessarily that the wrong symbols were being loaded it was just very ... unpredictable. Sometimes the source for a class would load. Sometimes it would popup a dialog box. (For the same class.) Sometimes the source for one class would load, but not for another. I could never quite get to the root of the issue - to where the original exception was being thrown. But like I said, I can look this up as well.

As you can imagine from my initial quite lengthy and probably overly verbose problem statement, and this response, I'm quite appreciative of thought out and detailed responses. However, I would offer this small bit of advice: 15 days is a very long time to have no response at all. Even a response that says, "We've read this and will get back to you" would help. Part of the reason that I find it so difficult to communicate effectively back and forth is because having several weeks between a posting and a response does not come across as "actively monitor[ing]". Even if you are, there's no way for someone like myself to know, unless there's some kind of indication.

Perhaps a github dedicated to .NET Backend would help here? Even if there's no source code (though I would reiterate my recommendation that this be pushed open source as soon as can practically be accomplished) it would help for the purposes of tracking issues, and also as having a single point of contact/reference. Trying to post here, and then Stack Overflow, the MSDN forums, etc, feels like a shotgun kind of approach. I mean I know each of these places has communities, etc, but for people who are just trying to use the product and don't care about community, it would be good to have a place where questions can get answered quickly. At least, quicker than 15 days. Also, issues could get tracked. For instance the issue that I described above (the missing method) has a Stack Overflow related to it, but the answer of which was basicaly "Don't upgrade to the latest version of .NET Backend" - obviously that's no longer the recommended workaround. But the developer responding to it asked a question, then never seemed to follow up.

Thank you, again, for taking the time to reply to this issue. As I've now started trying to set up the Auth on an Web API service, it makes me even more desirous to see Azure Mobile Service working in such a way that I can actually use it.

**Comment by lindydonna** [comment]
My apologies for how late my last response was, and thank you for giving us constructive criticism. This was my fault--your issue sparked a team discussion, which delayed matters. Ironically, we usually respond much more quickly! You raised a lot of good issues and we wanted to come up with the right way improve things in the future. In hindsight, I really should have posted *something*! :-/

Do you have a link to the StackOverflow thread where we didn't follow up?  We get automatic emails on anything tagged "azure-mobile"--it's possible that we have a bug where we aren't getting notified on comments. 

I'll bring it up with the team whether to make a new GitHub for backend issues, or use this one with the .NET runtime tag. Either way, we will add a note to the readme for the repo to make it clear that we welcome discussion of backend issues.

I hadn't thought about the client project making things confusing. I guess the best thing is to get into the habit of doing NuGet updates at the project level rather than solution level. We should add a note about this to our tutorials.

I'll look into the SignalR issue--we probably didn't update the package during the last build. Sorry for all the trouble that caused!  I'll look into the pdbs as well and make sure they all match.

I'm glad to hear that the auth support is working out--if you have any questions on best practices or particular providers, feel free to ask!

Finally, to get the pre-release NuGet packages packages, please email our team at mobileservices@microsoft.com. We should be ready in a few days, as we are testing right now.

**Comment by apollyonbob** [comment]
Okay so I wasn't able to trace down the dependency chain that caused the original problem, except that something updated Microsoft.Owin.Security.ActiveDirectory and that caused the update to JWT. Also I think I was conflating the Client SDK and WindowsAzure.ServiceBus, although the latter doesn't seem to have any strange dependencies. I'll watch out for it if it happens again I'll post a separate thread.

Here's the SO thread that I was referring to: http://stackoverflow.com/questions/26596519/jwtsecuritytokenhandler-set-certificatevalidator-method-not-found/27241624#27241624 and here's an MSDN thread where I'm asking about how to customize the authentication to add role-based security: https://social.msdn.microsoft.com/Forums/azure/en-US/6babace5-27f9-456d-9bc8-0f7b8219af2e/what-is-the-expected-pattern-for-rolebased-authentication-or-custom-claims-in-azure-mobile-service?forum=azuremobile

These have gotten responded to, but died out without resolution. That second one, I posted in the MSDN forums on the advice of some vendors (N3 LLC) that had gotten ahold of me asking if I needed any help in terms of Azure. I worked with them for awhile on this particular issue, but the last email I got from them wasn't terribly helpful, but that initial response on the MSDN Forum was a step in the right direction.

Should I repost the question in this GitHub? (Making a new thread for it, natch.)

**Comment by brettsam** [comment]
For those interested in trying out the pre-release server-side Nuget package that locks down the dependencies, I've made them all available at staging.nuget.org.

You can add staging.nuget.org to your package sources in VS with:

1. Tools -> Options -> Nuget Package Manager -> Package Sources
2. Add a new source with name `staging.nuget.org` and source `https://staging.nuget.org/api/v2/`

Then when you go to add or update references and select `staging.nuget.org` you should see version 450.

Donna covered the changes in her response above, but please let me know if you run into issues or have questions. 

**Only use these staging packages locally—you wouldn’t be able to deploy because the hosting environment doesn’t have the latest packages**.

I have no guaranteed ETA on when this will move to production, but I'll come back here to note when it does.

**Comment by lindydonna** [comment]
We forgot to update this thread--please try version 1.0.450.

@apollyonbob: you might be interested in the new Mobile App experience, that gives you full access to the underlying website configuration. In that environment, what you deploy is what is run--our backend runtime no longer has particular nugets that it will bind to. 

To learn more, see http://azure.microsoft.com/en-us/documentation/services/app-service/
