### ISSUE TITLE
Assembly version not matching Nuget version 1.3.1 (assemblies at version 3.1.0.0)

### ISSUE THREAD

**Issue by nrogoff** [Azure/azure-mobile-services#592]
The referenced assemblies report version 3.1.0.0 in Visual Studio for Nuget release version 3.1.1.
Shouldn't these match?

**Comment by lindydonna** [comment]
I think you must have transposed the numbers: you mean the NuGet is 1.3.1 (https://www.nuget.org/packages/WindowsAzure.MobileServices/) and VS says it is 1.3.0, correct?

**Comment by phvannor** [comment]
This is by design, our file version does not match 1:1 with the Nuget versioning scheme.  Assembly version is made only from the Major.Minor.0.0, and file version has the build in the form of Major.Minor.BuildDate.0.  

Any public API change should increment minor, breaking changes the major, and bug fixes not impacting the API get a new build date in the dll's file version and a new patch version for the nupkg.
