### ISSUE TITLE
[iOS] Pushed items aren't updated after 201 creation from server

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-services#596]
After items that are pushed from the client have a successful response of 201 created returned from the server, the item is not updated with system properties.

In my case, this is specifically the ms_version property is still nil on the client even though it is set in the backend database. Doing a pull from the server updates the property as expected.

Should this property be set on response from the server as it seems to be sending it back after creation properly?

**Comment by phvannor** [comment]
Version should be set post Insert if the server returns it.  The server (I believe) should be returning version as the ETag header, which the SDK parses into the __version on the object.  (I am not sure off the top of my head what the protocol is if the version comes back only in the body)

What are you seeing?  I wrote a quick test case, and it seems ok, but I could have mocked the response incorrectly from what is happening against a version of one of the runtimes.

**Comment by baumatron** [comment]
I could see #612 manifesting itself this way if you create an item on the server and there is a pending update to that item when the insert completes, which prevents the system properties from the server from being saved locally. I have a pull request with a unit test and fix here: #627.

**Comment by phvannor** [comment]
This is the same code idea as the thread on managed.  Your PR would result in essentially a last write wins policy on the client.  Its not always the correct policy to put the new version into the client copy (As we don't know if the server changed additional data beyond what we sent in our PATCH, etc)

To do this, ideally we'd have to compare what we sent and what we received, an verify no additional changes occurred.  

I think we need to flush out a local conflict handler, that is called in this case.  Essentially I think the developer of the app needs to chose to handle conflict now (by using the new version) or handle later when the next push happens (via their delegate)

Let me know your thoughts on this.  I'll take a look at the PR as well in more detail.

**Comment by baumatron** [comment]
Thanks for the feedback! I agree that there might be a need for some additional local handling of merge, since it is true that the server could modify the row and thus the fields of the item that were on the client would be missing that data in this case. The second option of handling the conflict later via the MSSyncContextDelegate during the subsequent push might be an option... will the handler have access to the current server version of the item in that case? In any case the second option sounds a little less than ideal since from the client's perspective this won't consistently be needed since its a timing thing. i.e., you could insert, push, update, push without any conflicts in some cases, but just because of network conditions or other timing differences such as time between user input have "conflicts" arise.

In the case where an insert would occur, followed by a push without any other local activity, we simply take the server item and write it to the database. In the existing MSSyncContextDelegate we would have the opportunity to take a look at a snapshot of the local item when the push started and also have a look at the result from the server if we'd like. The default behavior without a handler or errors is to just accept the server item, overwriting the local item.

In the case that currently fails, where an insert (or update) followed by a push and concurrent local update occurs, the first operation would provide the delegate with a snapshot of the item when the first operation started, along with the server item upon completion. Everything from the view of the handler would look identical to the case above, however the server item would get discarded at the end of the operation.

So, perhaps, as you mention, this is where the local conflict handler delegate could come in. The SDK would see when finishTableOperation is called on MSQueuePushOperation, that although there was no conflict with the server on that operation, saving it locally is an issue since the item in the database includes the local change made while the push was in progress (which it garners from the fact that there are pending operations for that item, which has nothing to do with version columns locally). It almost seems like it could be as simple as a client provided block or delegate that accepts the local item and server item and returns the item that should be written to the database. This way, if there are server-populated fields, they could be saved while still preserving local changes that need to be pushed to the server, and of course the system fields could be preserved from the server side as well. After this local merge handler is called, the queue would continue to be processed, pushing up the new merged item.

**Comment by phvannor** [comment]
Yes that could work.  As I mention in your code review, we can start by just verifying its safe to push version forward.  There should be good value in that piece, especially for apps where 1 user owns the record, and its highly unlikely the server would have modified it.

Long term, adding a block/delegate for handling this is better.  One thing the current PR doesn't address is people who may have an in memory copy from the store, and those may also want to update the version.  (So that may end up being a notification, a new error case when calling update()/delete(), triggering this same block/delegate, etc)

To answer your first question, right now we don't save the deltas/last synced server copy, so if you handled the conflict in the current delegate, it would be very hard to know what you need to handle before you sent the item to the server.

**Comment by phvannor** [comment]
Now tracked on https://github.com/Azure/azure-mobile-apps-ios-client/issues/29
