### ISSUE TITLE
Incremental Sync Javascript ? 

### ISSUE THREAD

**Issue by nikatlas** [Azure/azure-mobile-services#600]
Can someone tell me whether there is somekind of incremental sync in Javascript SDK? 
If not.. What about the system properties ? They dont come by default on the requests as i see. 
Is there a way to get the most recent UpdatedAt value from the sdk? 
Also, is there a way to set updatedAt to come on every request ? Even on add/update ?

**Comment by phvannor** [comment]
There is no sync code built on our JS SDK at this time.  All the system properties are present, since they are part of the server (And JS does support OC)  To get the values on your queries, you need to use the table.systemProperties option, or add a "__systemProperties=*" to your querystring.

updatedAt should be set automatically for you via a SQL trigger.  If you made the columns yourself/brought your own table, you could create a dummy table & inspect it to see the default triggers placed on it.

To get the most recent updatedAt for a table, you should be able to order by __updatedAt and set top to 1 in your query.  Just also set the systemProperty I mention above or the column will be hidden from you.

**Comment by nikatlas** [comment]
I see. 

I have already implemented custom incremental sync saving data to local storage for now. 

Again i would appreciate a honest response to whether is going to be a stable implementation soon :)

**Comment by lindydonna** [comment]
Can you be more specific about "stable implementation"?  Many of our features are supported in the JavaScript SDK, but unfortunately offline sync is not yet one of them. The JavaScript SDK is considered release quality, so if there's a specific bug, we'll definitely investigate!

**Comment by nikatlas** [comment]
Yeah actually im asking whether offline sync will be supported? If so, do you have a date estimation  ?

**Comment by lindydonna** [comment]
The long-term plan is to support the feature on JavaScript, but we have no ETA. In the meantime, I recommend a solution such as BreezeJS.
