### ISSUE TITLE
Managed SDK bug when not all fields are in JSON payload

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-services#636]
The managed SDK uses the first record in each page of the result set to determine the shape of the json object. However, this causes problems with the .NET backend, since its JSON serialization settings are to ignore default values (i.e., JsonFormatter.SerializerSettings.DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore)

There is a workaround, to change your WebConfig to always serialize all values. However, it's not obvious that is necessary, and the current behavior leads to strange values in the database (the whole column will be null).

Instead, the SDK should look at the SQLite table definition to determine what fields to deserialize.

**Comment by phvannor** [comment]
This has much larger implications to the offline fw than just this.  Default values being serialized out will break a lot of flows in offline, we need to change the .NET default.

Consider the following:
Local Table: { id: "1", version: 0, text: "A", complete: True }
Other App => { id: 1, version: 0*, text: "B", complete: False }
On Sync: {id: 1, version: 1, text: "B" } 
Local Post Aync: {id:1, version 1, text: "B", complete: True } (bad, now our state is out of whack)
Local: Edit text to C
Push: {id: 1, version: 1*, text: "C", complete: True }
Server: {id: 1, version: 2, text: "C", complete: True } (very bad)

**Comment by phvannor** [comment]
To get back to the issue, I think the client needs to throw and hard abort the sync, if the data model in the results is not equal to the columns in the defined table. 

This also goes to the reason we blocked $select in sync queries, we do not yet have the code to handle column differences like this.  I think when we work on the plan to allow $select we can also tackle this more elegantly.

If we want to support serializing our default values, we need to define a way to put them back in, and since we are dealing with JObjects we can't rely on the classes.

I'd expand that we need this error check in all 3 supported clients.
