### ISSUE TITLE
Conditions on enum does not work for SyncTables

### ISSUE THREAD

**Issue by PaulAchess** [Azure/azure-mobile-services#759]
Hi, I've had a little trouble with enums recently.

On server-side, I have an entity `MyEntity` with a property `Status` of enum type `StatusType`.
On mobile-side, same thing.

When I get entities with `GetSyncTable<BookEntry>().ToListAsync()` everything is correctly retrieved. I can also do a `.Where(e => e.Status == StatusType.Something)` after.

However, I could not, at all, put a condition on this enum like this : `GetSyncTable<BookEntry>().Where(e => e.Status == StatusType.Something).ToListAsync()`.

This returns an empty list. No matter what I tried (add JsonConverter, use int values, etc.) I could not make this comparison successful. If you have any info on this I'll gladly try anything you have, but I think this is a bug from the library.

Thanks for this amazing library.

**Comment by phvannor** [comment]
Given your query we will send a GET to /tables/bookentry?$filter=(Status eq 'Something')

In my quick test, I made an enum like so:
    
    public enum StatusType {
        Good = 1,
        Fair,
        Poor
    }

Then added a status property on my table.

Running the filter I got a GET to $filter=Status eq 'Good' and an array of results back as expected.

I did notice if the casing is wrong, the server throws an error, can you see what happens if you execute the query directly via PostMan/Fiddler/etc?

**Comment by PaulAchess** [comment]
I did the check and I'm guessing I'm on the wrong project actually.

I'm using the sync tables, and the issue completely goes away when I use GetTable<> instead of GetSyncTable<>. GetSyncTable<>, on the other hand, did not make any call.

Sorry for the inconveniance, I'll declare it on the sqlitestore project instead.

**Comment by PaulAchess** [comment]
Aaaaand I'm rushing too much, Sync tables are also on this project. My bad.

**Comment by phvannor** [comment]
Sorry I misread your post and totally missed you were taking about sync tables. Let me take another look.

**Comment by PaulAchess** [comment]
Yeah, that was not really explicit, I thought it was server-related. Seems not to be the case.

**Comment by phvannor** [comment]
OK, the way the .Net backend serializes enums (By default) is with CamelCasing.   I believe this is what you are hitting.

So if you enums are StatusType.Fair = 1, the server sends "fair" to the client, and the client atm just save that into the local db.

Then when you execute a local query using the same enum, it tries to find Status = 'Fair' and not Statue = 'fair'.  

One fix is to tell the server to not use camel case on your enum [JsonConverter(typeof(StringEnumConverter))] should do it.

Otherwise, your local query could do something like q.where(r => r.Status.toString().toLower() == StatusType.Fair.toString().toLower().  (Which is obv much uglier)'

Need to look at better fixes long term.

**Comment by PaulAchess** [comment]
Thanks for the quick answer. That might explains everything indeed.

The fix you offer seems the best, however I'm concerned about the current entries. For all users, without a synchronization they will still have the issue locally, won't they ?

I think I'll stick with the second solution. Even if it's uglier, at least I don't have a regression for users. In the meantime, I will implement the JsonConverter and I'll remove the ugly hack later on, when users will have synchronized all of their entries.

Again, thanks for you quick answers and feedback (and fixes !), you're the best.

**Comment by PaulAchess** [comment]
Regarding the `[JsonConverter(typeof(StringEnumConverter))]`, this does not seem to work, even if I add the converter with CamelCase

(I do this like that : `config.Formatters.JsonFormatter.SerializerSettings.Converters.Add(new StringEnumConverter { CamelCaseText = true });`)

**Comment by phvannor** [comment]
CamelCaseTest should be false for this fix.  The response from the server should use the exact casing of the Enum as its defined.  (CamelCaseText = true is the default the .Net backend sets up for you)  My very quick test worked ok, if the server response isn't updating, can you let me know what version of the backend nugets you are using?

Like you mentioned, the above is really only a good solution for a new app that isn't in the wild, since any synced data will not get adjusted until that record changes in the future.  

The proper fix is we need to see if the cilent's Linq to SQL translation can let you control how the resulting SQL statement is generated for an Enum.

**Comment by PaulAchess** [comment]
CamelCaseText = false does not seem to work either.

My version of Microsoft.Azure.Mobile.Server is 0.1.508.
The project is part of the Azure App Services

**Comment by phvannor** [comment]
My testing was on the Mobile Service .Net side, I didn't try on the newer Mobile App side.  I'll need to play around with it to see how you override the serialization correctly there.

**Comment by nadjibus** [comment]
Hi Guys. I also hit this problem when filtering with an enum value. Any fix ETA for this bug or is there a workaround?

**Comment by phvannor** [comment]
Putting the "[JsonConverter(typeof(StringEnumConverter))]" attribute on the enum itself (not the property using the enum) will work for sending them in PascalCase to the client.
