### ISSUE TITLE
Android- data getting null in mobile after incremental sync.

### ISSUE THREAD

**Issue by rajeesh7** [Azure/azure-mobile-services#801]
I have changed a data in server side and then made a mobile sync. Sometimes this change is not getting in mobile side. 

While debugging,  the web service is carrying data but it is not reaching in android. This is not occurring every time.  First  I thought this was  related to some connectivity issues. But after  implementing proper logs  the exception revealed that the issue is with the incremental push. 

The server made changes are making conflict with the  android sdk and the changes are reverted.

the exceptions is as follows.

com.microsoft.windowsazure.mobileservices.MobileServiceException: {"$id":"1","message":"The operation failed due to a conflict: 'Violation of PRIMARY KEY constraint 'PK_Xxxxxtablename'. Cannot insert duplicate key in object 'dbo.Xxxxxtablename'. The duplicate key value is (2, 834c8570-355c-4b80-bef9-b9006dc609cb, 341).\r\nThe statement has been terminated.'."}

This is not getting with every sync but  a frequent issue.

Actually what it needs is a  http patch request but the sdk is sending this  as  http post. I think this causes the error

Could anyone help me in getting a solution.

**Comment by phvannor** [comment]
Usually this type of error occurs when the client attempted to send a queued Insert command to the server, but the response was lost due to network conditions.

So the server actually got the insert, but the client never got the ACK that it did, so keeps trying and now you get a conflict response.  

What you need to do, is if you haven't made further changes is call cancelAndUpdateItem from the error object in response to push.  If you have made changes, then you need to do the above, and either add a new queued update or make the call to the server before canceling the insert.

@soninaren may be able to give you the more specific code in Java / point you to a doc as an example.
