### ISSUE TITLE
There's no Messaging Framework in latest iOS 2.x SDK

### ISSUE THREAD

**Issue by mballinas** [Azure/azure-mobile-services#812]
I dowloaded the latest iOS 2.x SDK and it does not contain the Windows Azure Messaging Framework, only the Mobile Services Framework. The 1.2.4 SDK contains the Messaging Framework but doesn't include BitCode and I'm getting compiling errors in Xcode 7. Thanks in advance!

**Comment by phvannor** [comment]
You are correct the messaging fw is not in the 2.* download. Unfortunately, there isn't a build of the messaging FW that includes BitCode, etc yet.  So the copy in 1.2.4 is the latest set of bits.

For now you will need to manually build it from their repo: https://github.com/Azure/azure-notificationhubs

There was an issue tracking this (https://github.com/Azure/azure-notificationhubs/issues/21) but it looks like they closed it after a manual build.  Probably should be reopened, so that a new build can be made and released.
