### ISSUE TITLE
MobileServicePushFailedException with status Complete and no error

### ISSUE THREAD

**Issue by PaulARoy** [Azure/azure-mobile-services#869]
Hi there,

First of all thanks for this amazing library!

I am using SQLiteStore and the managed version of the framework on a PCL project (then used by Xamarin on Android, iOS and WP).

Often I experience a `MobileServicePushFailedException` having the status « Complete » and absolutely no error (`exception.PushResult.Errors`) during the synchronization.

I have trouble understanding why and knowing if there is anything I can do about it.

Has anyone ever seen this? Could it be a bug?

Note: I do not know if it could impact the result but for full transparency I am using a workaround for 409 errors as seen [here](https://social.msdn.microsoft.com/Forums/azure/en-US/e595ecce-417d-4cc0-b68b-f15cf692f555/the-operation-failed-due-to-a-conflict-violation-of-primary-key).

**Comment by seanfisher** [comment]
@PaulARoy I know this is closed, but we've been getting the same issue with the status being complete and no PushResult.Errors. Sometimes we see that the exception has an inner exception with more clues. For example, our server was returning a 500 error in the form of an HTML yellow screen of death. Azure Mobile Services saved this HTML page into the `__errors` table and when it tried to deserialize it as if it were JSON it threw a serialization exception (since '<', the first character in the HTML page, was not valid JSON), which was then wrapped in a MobileServicePushFailedException like the one you describe.

Have you found any other cases where this happens?

**Comment by PaulARoy** [comment]
This is the repo for the old package which is why I closed the issue: it was not reported on the right repo.

More informations on this issue: https://github.com/Azure/azure-mobile-apps-net-client/issues/70
