### ISSUE TITLE
Insertion failure when foreignkey reference changed before sync

### ISSUE THREAD

**Issue by rndthoughts** [Azure/azure-mobile-services#871]
Consider the following actions:

1. Insert record into table 1
2. Inset record into table 2
3. Update foreign key value in table 1 to relate to record in table 2.

When a sync is performed, the process attempts to insert the record in table 1 first and then fails because the record in table 2 has not been inserted yet but the record in table 1 points to it as it as been updated.  If the steps are changed so:

1. Insert record into table 2
2. Insert record into table 1
3. Update foreign key value into table 1 to relate to record in table 2.

This process of course works.

However, as there doesn't appear to be any constraint support in the version of SqlLite used on iOS, how do we deal with the first example if the sync framework merges the insert and update?

**Comment by rndthoughts** [comment]
any update on this?

**Comment by shrishrirang** [comment]
Currently, this is a known limitation of the [offline sync logic](https://github.com/Azure/azure-mobile-services/blob/master/sdk/iOS/src/MSTableOperation.m#L105). The sync logic condenses multiple updates to the same rows as an optimization so that we don't end up replaying all operations performed on the local store.

I will look at this to see how best to support foreign keys without compromising performance. If you have any suggestions/thoughts, I will be happy to know.

**Comment by seanfisher** [comment]
We are also struggling with this issue. Merging update operations with the original insert operation breaks the paradigm of keeping a queue of operations so that issues like these (foreign key issues) are solved. It seems to me as though you can't have these two principles work together. You can either have all operations queued up in the same order that they were performed or you can merge operations for performance, but you can't have both and expect it to work correctly.

In our case we would much rather send two requests to the server (an insert and then an update later) than to deal with working around this issue.

@rndthoughts How have you worked around this issue?

@shrishrirang Maybe having an opt-in behavior of maintaining the queue exactly as you perform it locally?

**Comment by shrishrirang** [comment]
@seanfisher One of the reasons we condense multiple operations into one is that we do not have values corresponding to old operations if a new operation edits the same row. For example, if the following operations are performed:
```
insert in table A VALUES {id: a, value: a1, foreignkey: null}
insert in table B VALUES {id: b, value: b1}
update table A VALUES {id: a, value: a2, foreignkey: b}
```

The operations table - if operations aren't merged - will look like this:
```
{insert, a}
{insert, b}
{update, a}
```

and the tables at this point of time will look like the following:
```
tableA => {id: a, value: a2, foreignKey: b}
tableB => {id: b, value: b1}
```

Note that we do not store the records in the operation table. We just store their IDs.

If a push is performed now, while the first entry from the operations table is processed, we will begin by inserting `{id: a, value: a2, foreignKey: b}` on the server. This is a violation of the foreign key constraint as the referenced row hasn't been pushed yet.

So just turning condensing off isn't going to help. Enabling change tracking or doing an equivalent of it ourselves can help (in retrieving historical values), but we want to avoid going down that path.

Over the next few weeks we will be reviewing the design as a whole to see how the foreign key limitation and some other related issues can be solved. As always, suggestions are always welcome :)

**Comment by adrianhall** [comment]
We are not working on azure-mobile-services - please re-file if necessary for azure-mobile-apps.  It's already filed, per the above.
