### ISSUE TITLE
iOS - userId on MSUser does not match user.id in database backend NodeJS code while logging in with Google

### ISSUE THREAD

**Issue by ufoxp** [Azure/azure-mobile-services#883]
From my preliminary research it looks like "endUrl" passed into SDK MSLoginView -callCompletion:orError: by the server is incompatible with backend user.id - at least when logging in with Google (I did not test other login providers).

**Comment by shrishrirang** [comment]
We are working on a fix for this issue. We expect the issue to be fixed in about 2 weeks. No changes to your code would be needed once we fix this on our side.

If you inspect user.claims on the backend, you will notice two properties: stable_sid and sub. The bug is due to the fact that currently the userId you see on the client matches user.claims.stable_sid while the one on server matches user.claims.sub. After the bug is fixed both will correspond to sub.

**Comment by ufoxp** [comment]
Judging by the name itself stable_sid look "more stable". Does it mean that after fix client user id will be changing in some conditions? That looks more like a regression than fix? Or is it part of fix described at https://social.msdn.microsoft.com/Forums/azure/en-US/062087be-71b0-41eb-9411-cd2cd2a8c067/user-sid-has-changed-while-using-the-same-fb-account-to-logon-to-mobile-apps?forum=azuremobile which means that the developers will be able (if they so choose) to switch to stable id algorithm on both sides?

**Comment by brettsam** [comment]
You can enable stable_sid to become the default sid by setting an App Setting of `WEBSITE_AUTH_HIDE_DEPRECATED_SID` to `true` in the portal. This will move `stable_sid` to become the user id (and remove `stable_sid` from the claims). You should then have the same id returned on the client.

This is a new feature and hasn't been documented widely. It will eventually become the default behavior for all new apps, but you can force it with the key I've noted above.

Can you give that a try and see if it works as you expect?

**Comment by ufoxp** [comment]
Yes, WEBSITE_AUTH_HIDE_DEPRECATED_SID seems to do what I wanted. None the less I hope the initally reported bug will be fixed as well :)
