### ISSUE TITLE
Xamarin Forms NullReferenceException on LoginAsync() with Facebook on Android API level 23

### ISSUE THREAD

**Issue by adrianhara** [Azure/azure-mobile-services#899]
I'm using `MobileServiceClient.LoginAsync()` in a Xamarin Forms app to login with Facebook. The implementation is as recommended split into the iOS and Android projects. For Android the call to `LoginAsync` is sent the `MainActivity` as the context and the Facebook provider as provider.

The problem is that on a 10" Marshmallow (6.0.0) tablet (API 23), which I'm running in the VS Emulator, the call throws a NullReferenceException immediately after the successful login on the Facebook webview that comes up. 

The same exact code works fine on a KitKat 4.4 tablet (API 19).

Unfortunately there is no helpful/meaningful stack trace to the exception to indicate the cause.

I have tried it using Xamarin Forms 2.0 and 2.3.0.49 (latest version). Both yield the same behavior.

Any ideas? Is it maybe a known issue?

**Comment by ltaljaard** [comment]
I had the same. Only on Android and only on specific API versions. Try this, I know it seems mad but it actually works for me. Put a try..catch block directly after the call to LoginAsync and then put a breakpoint within the Try block (and within the Catch block to prove to yourself that this actually works). That effectively absorbs the null pointer error that would otherwise occur when you were to put a breakpoint anywhere ELSE further down in your app. If this works for you then we have evidence that it’s a generic bug and then we can log it as such. 

    public class Authenticate_UI : IAuthenticate_UI
    {
        // The following is from: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-users/
        public async Task<MobileServiceUser> Authenticate(IMobileServiceClient client, MobileServiceAuthenticationProvider provider)
        {
            MobileServiceUser user = null;
            try
            {    // Sign in with Facebook login using a server-managed flow.
                user = await client.LoginAsync (Forms.Context, provider);
            }
            catch (Exception ex)
            {    user = null;
            }



//***********************************************************************************
            try
            {    int ANDROID_DEBUG_BUG_WORKAROUND_NULPOINTEREXCEPTION_PUT_FIRST_BREAKPOINT_AFTER_LOGINASYNC_HERE = 1;
            }
            catch(Exception ex)
            {    int ANDROID_DEBUG_BUG_WORKAROUND_can_now_put_bp_wherever_you_want = 1;
            }
//***********************************************************************************



            return user;
        }
...
     }

**Comment by adrianhara** [comment]
Thanks for the suggestion! I tried it and it seems to work in Debug mode, if I actually hit the breakpoints. Running without any breakpoints or without the debugger attached still crashes though :(

**Comment by adrianhara** [comment]
Anyone?

**Comment by adrianhall** [comment]
Closing as we have moved this over to the right repo.
